name: setup_node
description: Setup Node, and install Pnpm
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.2.0

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v5
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install
      # `--no-frozen-lockfile` is used to work around Dependabot issue that doesn't update the lock.
      run: pnpm i --no-frozen-lockfile
      shell: bash
